In [3]:
with open('life-expectancy.csv', 'r') as f:
    lines = f.readlines()
    rows = []
    for line in lines:
        s = line.split(',') 
        rows.append(s)

In [14]:
lf = []
for row in rows[1:]:
    lf.append(float(row[3].strip()))

In [17]:
min(lf)

17.76

In [20]:
year = '1999'

def get_average(lst: list) -> list:
    return sum(lst) / len(lst)
max_value = max([ [float(row[3].strip()), row[0], row[2] ] for row in rows])
min_value = min([ [float(row[3].strip()), row[0], row[2] ] for row in rows])
all_life = [ float(row[3].strip()) for row in rows ]
average = get_average(all_life)
top3 = sorted([ [float(row[3].strip()), row[0], row[2] ] for row in rows], reverse=True)[:3]

In [21]:
top3

[[86.751, 'Monaco', '2019'],
 [86.56, 'Monaco', '2018'],
 [86.325, 'Monaco', '2017']]

In [22]:
max_value

[86.751, 'Monaco', '2019']

In [23]:
import pandas as pd
df = pd.DataFrame(dataframe)

In [24]:
df

Empty DataFrame
Columns: []
Index: []

In [29]:
year_list = [row[2] for row in rows]
averages = {}
for row in rows:
    for year in year_list:
        if row[2] == year:
            averages.update({year:row[3]})

In [30]:
averages

{'1950': '48.831\n',
 '1951': '49.04\n',
 '1952': '49.46\n',
 '1953': '49.886\n',
 '1954': '50.317\n',
 '1955': '50.754\n',
 '1956': '51.197\n',
 '1957': '51.645\n',
 '1958': '52.098\n',
 '1959': '52.556\n',
 '1960': '53.019\n',
 '1961': '53.483\n',
 '1962': '53.946\n',
 '1963': '54.403\n',
 '1964': '54.849\n',
 '1965': '55.274\n',
 '1966': '55.671\n',
 '1967': '56.034\n',
 '1968': '56.362\n',
 '1969': '56.656\n',
 '1970': '56.913\n',
 '1971': '57.135\n',
 '1972': '57.329\n',
 '1973': '57.509\n',
 '1974': '57.688\n',
 '1975': '57.892\n',
 '1976': '58.15\n',
 '1977': '58.47\n',
 '1978': '58.85\n',
 '1979': '59.274\n',
 '1980': '59.731\n',
 '1981': '60.203\n',
 '1982': '60.65\n',
 '1983': '61.025\n',
 '1984': '61.28\n',
 '1985': '61.356\n',
 '1986': '61.199\n',
 '1987': '60.792\n',
 '1988': '60.136\n',
 '1989': '59.235\n',
 '1990': '58.1\n',
 '1991': '56.749\n',
 '1992': '55.243\n',
 '1993': '53.653\n',
 '1994': '52.044\n',
 '1995': '50.48\n',
 '1996': '49.009\n',
 '1997': '47.661\n',
 '1998': '46.466\n',
 '1999': '45.461\n',
 '2000': '44.649\n',
 '2001': '44.01\n',
 '2002': '43.523\n',
 '2003': '43.195\n',
 '2004': '43.065\n',
 '2005': '43.241\n',
 '2006': '43.853\n',
 '2007': '44.947\n',
 '2008': '46.504\n',
 '2009': '48.449\n',
 '2010': '50.64\n',
 '2011': '52.896\n',
 '2012': '55.032\n',
 '2013': '56.897\n',
 '2014': '58.41\n',
 '2015': '59.534\n',
 '2016': '60.294\n',
 '2017': '60.812\n',
 '2018': '61.195\n',
 '2019': '61.49',
 '1770': '28.7\n',
 '1925': '58.5\n',
 '1923': '57.5\n',
 '1933': '60.880001\n',
 '1943': '64.300003\n',
 '1830': '40.939999\n',
 '1850': '29.3\n',
 '1870': '29.7\n',
 '1900': '32\n',
 '1913': '34.1\n',
 '1940': '38\n',
 '1875': '41.450001\n',
 '1880': '39.41\n',
 '1885': '44.57\n',
 '1890': '45.209999\n',
 '1895': '45.41\n',
 '1905': '50.299999\n',
 '1910': '29\n',
 '1915': '55.099998\n',
 '1920': '31\n',
 '1930': '32\n',
 '1935': '60.889999\n',
 '1945': '65.580002\n',
 '1921': '58.200001\n',
 '1922': '58.099998\n',
 '1924': '58.5\n',
 '1926': '57.900002\n',
 '1927': '59.400002\n',
 '1928': '58.299999\n',
 '1929': '58.5\n',
 '1931': '60.299999\n',
 '1932': '61\n',
 '1934': '60.23\n',
 '1936': '60.349998\n',
 '1937': '61.049999\n',
 '1938': '62.389999\n',
 '1939': '63.07\n',
 '1941': '63.799999\n',
 '1942': '64.589996\n',
 '1944': '65.089996\n',
 '1946': '66.279999\n',
 '1947': '66.690002\n',
 '1948': '67.25\n',
 '1949': '67.629997\n',
 '1881': '45.055\n',
 '1891': '44.43\n',
 '1901': '49.299999\n',
 '1903': '50.599998\n',
 '1911': '53.400002\n',
 '1876': '42.665001\n',
 '1886': '44.584999\n',
 '1896': '47.07\n',
 '1906': '50.099998\n',
 '1841': '45.110001\n',
 '1842': '40.994999\n',
 '1843': '41.560001\n',
 '1844': '41.240002\n',
 '1845': '42.169998\n',
 '1846': '40.150002\n',
 '1847': '38.514999\n',
 '1848': '39.889999\n',
 '1849': '37.68\n',
 '1851': '40.950001\n',
 '1852': '40.41\n',
 '1853': '39.985001\n',
 '1854': '39.48\n',
 '1855': '40.740002\n',
 '1856': '42.470001\n',
 '1857': '40.924999\n',
 '1858': '39.544998\n',
 '1859': '40.404999\n',
 '1860': '41.945\n',
 '1861': '41.619999\n',
 '1862': '42.130001\n',
 '1863': '40.369999\n',
 '1864': '39.584999\n',
 '1865': '39.75\n',
 '1866': '40.084999\n',
 '1867': '41.994999\n',
 '1868': '41.700001\n',
 '1869': '41.34\n',
 '1871': '41.134998\n',
 '1872': '42.720001\n',
 '1873': '43.290001\n',
 '1874': '42.105\n',
 '1877': '43.689999\n',
 '1878': '42.040001\n',
 '1879': '43.505001\n',
 '1882': '43.985001\n',
 '1883': '44.014999\n',
 '1884': '43.634998\n',
 '1887': '45.080002\n',
 '1888': '46.279999\n',
 '1889': '45.93\n',
 '1892': '45.59\n',
 '1893': '44.68\n',
 '1894': '48.275002\n',
 '1897': '46.445\n',
 '1898': '46.139999\n',
 '1899': '45.244999\n',
 '1902': '50.5\n',
 '1904': '49.599998\n',
 '1907': '50.200001\n',
 '1908': '51.900002\n',
 '1909': '52.799999\n',
 '1912': '54.099998\n',
 '1919': '55.299999\n',
 '1831': '38.939999\n',
 '1917': '54\n',
 '1918': '47.200001\n',
 '1775': '38.09\n',
 '1835': '47.119999\n',
 '1836': '45.110001\n',
 '1837': '39.549999\n',
 '1838': '40.560001\n',
 '1839': '39.830002\n',
 '1840': '43.939999\n',
 '1914': '54.599998\n',
 '1916': '54.200001\n',
 '1800': '28.5\n',
 '1820': '29\n',
 '1755': '36.5\n',
 '1765': '35.93\n',
 '1785': '33.43\n',
 '1795': '36.5\n',
 '1805': '41\n',
 '1815': '40.41\n',
 '1825': '45.220001\n',
 '1816': '41.73\n',
 '1817': '40.27\n',
 '1818': '40.84\n',
 '1819': '36.93\n',
 '1821': '38.119999\n',
 '1822': '42.73\n',
 '1823': '40.470001\n',
 '1824': '44.939999\n',
 '1826': '43.060001\n',
 '1827': '42.630001\n',
 '1828': '41.43\n',
 '1829': '36.16\n',
 '1832': '40.810001\n',
 '1833': '40.889999\n',
 '1834': '38.509998\n',
 '1751': '38.369999\n',
 '1752': '35.34\n',
 '1753': '39.77\n',
 '1754': '37.43\n',
 '1756': '36.18\n',
 '1757': '33.759998\n',
 '1758': '38.119999\n',
 '1759': '38.150002\n',
 '1760': '39.66\n',
 '1761': '37.759998\n',
 '1762': '32.419998\n',
 '1763': '35.369999\n',
 '1764': '36.240002\n',
 '1766': '38.040001\n',
 '1767': '38.16\n',
 '1768': '36.189999\n',
 '1769': '34.650002\n',
 '1771': '35.369999\n',
 '1772': '27.68\n',
 '1773': '39.09\n',
 '1774': '40.529999\n',
 '1776': '41.470001\n',
 '1777': '38.080002\n',
 '1778': '37.740002\n',
 '1779': '32.759998\n',
 '1780': '42.639999\n',
 '1781': '37.759998\n',
 '1782': '36.610001\n',
 '1783': '35.810001\n',
 '1784': '31.4\n',
 '1786': '37.84\n',
 '1787': '40.220001\n',
 '1788': '38.970001\n',
 '1789': '31.17\n',
 '1790': '33.549999\n',
 '1791': '38.400002\n',
 '1792': '39.779999\n',
 '1793': '37.919998\n',
 '1794': '40.360001\n',
 '1796': '38.82\n',
 '1797': '40.310001\n',
 '1798': '38.93\n',
 '1799': '39.290001\n',
 '1801': '36.849998\n',
 '1802': '40.130001\n',
 '1803': '40.02\n',
 '1804': '39.650002\n',
 '1806': '36.139999\n',
 '1807': '38.720001\n',
 '1808': '40.580002\n',
 '1809': '26.860001\n',
 '1810': '31.940001\n',
 '1811': '34.540001\n',
 '1812': '35.049999\n',
 '1813': '41.25\n',
 '1814': '38.549999\n',
 '1543': '33.939999\n',
 '1548': '38.82\n',
 '1553': '39.59\n',
 '1558': '22.379999\n',
 '1563': '36.66\n',
 '1568': '39.669998\n',
 '1573': '41.060001\n',
 '1578': '41.560001\n',
 '1583': '42.700001\n',
 '1588': '37.049999\n',
 '1593': '38.049999\n',
 '1598': '37.82\n',
 '1603': '38.529999\n',
 '1608': '39.59\n',
 '1613': '36.790001\n',
 '1618': '40.310001\n',
 '1623': '33.389999\n',
 '1628': '39.689999\n',
 '1633': '39.720001\n',
 '1638': '34.029999\n',
 '1643': '36.32\n',
 '1648': '39.740002\n',
 '1653': '39.139999\n',
 '1658': '33.040001\n',
 '1663': '33.27\n',
 '1668': '32.48\n',
 '1673': '37.41\n',
 '1678': '32.400002\n',
 '1683': '31.27\n',
 '1688': '35.93\n',
 '1693': '36.349998\n',
 '1698': '38.060001\n',
 '1703': '38.470001\n',
 '1708': '38.5\n',
 '1713': '36.889999\n',
 '1718': '35.75\n',
 '1723': '35.490002\n',
 '1728': '25.34\n',
 '1733': '36.34\n',
 '1738': '35.259998\n',
 '1743': '34.27\n',
 '1748': '36.470001\n'}